# https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
# GITHUB_REF_NAME (github.ref_name)- branch or tag that triggerred the workflow
# GITHUB_SHA (github.sha) - sha that triggerred the workflow
# GITHUB_REPOSITORY (github.repository) - owner/repo name
# GITHUB_REPOSITORY_OWNER (github.repository_owner) - owner only name
# GITHUB_EVENT_NAME (github.event_name) - name of event that triggered this
# usage ${THE-GITHUB-VAR}

name: Perform Checks

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      cmd:
        description: 'lint, test, debug'
        default: 'debug'
        required: true
      tag:
        description: 'Enter branch or tag'
        default: 'main'
        required: true
  issue_comment:
    types: [created]
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  TAG: ${{ github.event.inputs.tag || 'main' }}
  COMMAND: ${{ github.event.inputs.cmd || 'lint' }}

# each job run in parallel by default


jobs:
  trigger-workflow_dispatch-debug: # job
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.cmd == 'debug' # one if per job
    steps:
      - name: Workflow Dispatch Run Debug Show GitHub context
        # if: github.event.inputs.cmd == 'debug'
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: echo "$GITHUB_CONTEXT"
        shell: bash
  trigger-workflow_dispatch-lint: # job
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.cmd == 'lint' # one if per job
    steps:
      - name: Selected Branch/tag
        run: echo "Selected Branch = ${{ github.event.inputs.tag }}"
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        # with:
        #   node-version: 18 // lts
      - name: Install Dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint
  trigger-comment-debug: # debug job
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/debug')
    steps:
      - name: Command Run Debug Show GitHub context
        if: startsWith(github.event.comment.body, '/debug')
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: |
          echo "Version 0.0.6"
          echo "$GITHUB_CONTEXT"
        shell: bash
  trigger-comment-test: # test job
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/test')
    steps:
      - name: Comment Run Test
        if: 
        run: echo "comment Test run"
  trigger-comment-lint: # lint job
    # needs: <job name of job required to succeed to run this job>
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' # one if per job
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/lint')
    steps:
      - name: Comment Run lint
        run: echo "comment lint run"
      - name: Selected Branch/tag
        run: echo ${{ github.ref_name }}
      - name: Checkout Repository
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.inputs.tag }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        # with:
        #   node-version: 18 // lts
      - name: Install Dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint
