name: Restart Aliyun Function Compute

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag_gr:
        description: 'git repo branch or tag'
        default: 'main'
        required: true
      app_env:
        default: 'dev'
        description: 'application environment dev or prd'
        required: true
      tag_cr:
        description: 'container tag'
        default: 'latest'
        required: true
      accel_cr:
        description: 'container acceleration: None or Default'
        default: 'None'
        required: true
      timeout_s:
        description: 'timeout in seconds'
        default: '500'
        required: true
      # sts-token:
      #   description: 'StsToken, required in StsToken mode'
env:
  AK_ID: ${{ secrets.AK_ID }}
  AK_SECRET: ${{ secrets.AK_SECRET }}
jobs:
  update_function:
    #vif: vars.BUCKET_TYPE == 'oss'
    # name: Deploying To Aliyun OSS - Node Version TBD
    runs-on: ubuntu-latest
    name: Restart FC
    steps:
      - name: Workflow Inputs
        run: |
          echo "branch/tag: ${{ github.event.inputs.tag_gr }}"
          echo "env (dev/prd): ${{ github.event.inputs.app_env }}"
          echo "timeout (s): ${{ github.event.inputs.timeout_s }}"
      - name: Add checkout plugin
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag_gr }}
      - name: Update Function
        # alias-cicd is a name (you can use other names) defined in the command creating config with access keys/
        run: |
          npx @serverless-devs/s config add --AccessKeyID $AK_ID --AccessKeySecret $AK_SECRET -a alias-cicd
          cd apps/common/deploy/${{ github.event.inputs.app_env }}
          sed -i.bak "s/XX_TIMEOUT_S_XX/${{ github.event.inputs.timeout_s }}/g" s.yaml
          sed -i.bak "s/XX_ACCEL_CR_XX/${{ github.event.inputs.accel_cr }}/g" s.yaml
          sed -i.bak "s/XX_TAG_CR_XX/${{ github.event.inputs.tag_cr }}/g" s.yaml
          cat s.yaml
          npx @serverless-devs/s deploy --use-local
