# This is a basic workflow that is manually triggered
# try to use as much shell scripting a possible
# actions appear from default branch - https://github.community/t/workflow-files-only-picked-up-from-master/16129/2
name: Test Action

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      secret_key:
        description: 'key to required secret'
        default: ''
        required: false
env:
  SECRET_KEY: ${{ github.event.inputs.secret_key || 'No Key' }} 
jobs:
  test-action:
    name: Running Test Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Add checkout plugin
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Testing
        uses: ./.github/myactions/make-tag
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run commands 
        run: |
          echo `node -v`
          echo $SECRET_KEY
          echo The secrets ${{ secrets.CR_USERNAME }}
          echo The vars ${{ vars.CR_HOST }}
          echo The ENV ${{ env.COMMIT_SHORT_SHA }}
